### DISCUSSION TITLE
Is release-drafter conditional on publishing to PyPI or TestPyPI?

### DISCUSSION THREAD

**Discussion by eyllanesc** [cjolowicz/cookiecutter-hypermodern-python#1180] [Q&A]
Reviewing the workflow [release.yml](https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/release.yml), I see that if for some reason the publication fails in PyPI or TestPyPI then release-drafter is not executed:

https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/ce04c553fb4c6786b97ce5401f6e3fada64bf0f1/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/release.yml#L58-L79

I think it should be executed anyway, and if so then a possible solution is: 

```yml
      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.19.0
        if: always() # <---
        with:
          publish: {{ "${{ steps.check-version.outputs.tag != '' }}" }}
          tag: {{ "${{ steps.check-version.outputs.tag }}" }}
        env:
          GITHUB_TOKEN: {{ "${{ secrets.GITHUB_TOKEN }}" }}
```

Another option would be to move `release-drafter` before `PyPI` and `TestPyPI`.

@cjolowicz What do you think?
