### ISSUE TITLE
Which files should I remove if I dont want to release on PyPi or readthedocs/Sphinx

### ISSUE THREAD

**Issue by slidenerd** [cjolowicz/cookiecutter-hypermodern-python#1232]
Its a private repo and I would like to keep everything on GitHub. which files do you recommend I remove in order to achieve this?

**Comment by juftin** [comment]
You should have GitHub Actions file @ `.github/workflows/release.yml`, you'll remove these lines for publishing to PyPI:
```yaml
      - name: Publish package on PyPI
        if: steps.check-version.outputs.tag
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

      - name: Publish package on TestPyPI
        if: "! steps.check-version.outputs.tag"
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
```
