### ISSUE TITLE
Safety Errors about Tornado < 6.3.2

### ISSUE THREAD

**Issue by natescherer** [cjolowicz/cookiecutter-hypermodern-python#1349]
Just a heads up that by default, safety errors out because of vulnerabilities in tornado (required by livereload, which is required by sphinx-autobuild). https://pyup.io/v/59071/f17/ indicates tornado 6.3.2 is required to fix the vuln, but >=6.3 requires python 3.8. Updating the below in the pyproject.toml will fix:

``` toml
[tool.poetry.dependencies]
python = "^3.8"
```
