### ISSUE TITLE
Release with salsify/action-detect-and-tag-new-version

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#292]
https://github.com/release-drafter/release-drafter/pull/424#issuecomment-598830640

**Comment by cjolowicz** [comment]
```yaml
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Check and Release New Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check for Version Change
        id: check-version
        uses: salsify/action-detect-and-tag-new-version@v1

      - name: Publish New Package Version
        if: steps.check-version.outputs.tag
        run: |
          # Publishes the package to our internal registry

      - name: Publish Release Notes
        if: steps.check-version.outputs.tag
        # We can switch to a tagged version once 5.8 is published
        uses: release-drafter/release-drafter@f677696
        with:
          publish: true
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Alternate take:

```yaml
     - name: Publish Release Notes
        uses: release-drafter/release-drafter@f677696
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
