### ISSUE TITLE
Configure Codecov for 100% coverage

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#40]
Include the following **coverage.yml** in generated projects:

```yaml
coverage:
    status:
        patch:
            default:
                target: '100'
        project:
            default:
                target: '100'
```

See https://docs.codecov.io/docs/codecov-yaml

The file above is from [urllib3](https://github.com/urllib3/urllib3/blob/6b328933a7cc55d0b5ff443d03fe2b99761e7f57/codecov.yml).
