### ISSUE TITLE
Coverage check on GA does not combine coverage data

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#468]
On GitHub Action, each test run triggers the coverage session. Due to the fact that the workflow runs every session and interpreter separately, coverage can fail in CI even though the combined coverage would have reached the target, and local tests succeeded. By contrast, the Codecov check will succeed and combine coverage across interpreters (and platforms).

Example: https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/pull/324

One way to fix this is to never fail the workflow from coverage, and rely on Codecov exclusively. Ideally, we would still produce a terminal report with Coverage.py, just without failing the job. An open question is how well we can ensure that local testing and CI agree in their final verdict on code coverage. (For example, note that local testing does not combine coverage across platforms, while Codecov does.)

**Comment by oncleben31** [comment]
What about having a parameter passed to nox to not trigger the coverage session.
And we launch a dedicated coverage session in a specific GA job after all the elements of the strategy matrix are done.

**Comment by oncleben31** [comment]
I have done a mockup using `session.interactive` to differentiate the logics between local and GitHub Action.

```
@nox.session(python=python_versions)
def tests(session: Session) -> None:
    """Run the test suite."""
    install_package(session)
    install(session, "coverage[toml]", "pytest", "requests-mock")
    try:
        session.run("coverage", "run", "--parallel", "-m", "pytest", *session.posargs)
    finally:
        if session.interactive:
            session.notify("coverage")
```
Now the test session won't run the coverage check in GA.

I've added a step in the `build` job to upload the `.coverage.*` data in GitHub Action artefact:
```
      - name: "Upload coverage data"
        uses: "actions/upload-artifact@v2"
        with:
          name: coverage-data
          path: ${{ github.workspace }}/.coverage.*
```

And I've added a job dedicated to coverage to download the data from the artifact, combine them, show the report and generate the xml file before uploading on codecov:

```
  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version
      - name: Install Nox
        run: |
          pip install --constraint=.github/workflows/constraints.txt nox
          nox --version

      - name: "Download coverage data"
        uses: actions/download-artifact@v2
        with:
          name: coverage-data

      - name: Combine coverage data and display human readable report
        run: |
          nox --force-color --session=coverage

      - name: Create coverage report
        run: |
          nox --force-color --session=coverage -- xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.10
```

The mockup runs in a personal project. See this PR: https://github.com/hacf-fr/meteofrance-api/pull/25
