### ISSUE TITLE
Use the $default-branch token in GA workflows

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#561]
Use the `$default-branch` token in workflows instead of hardcoding the `master` branch.

```yaml
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
```

https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

See https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/

**Comment by cjolowicz** [comment]
Labelling as a bug because repositories are now generated with `main` as the default branch, by default.

**Comment by cjolowicz** [comment]
This does not appear to work. Presumably the `$default-branch` token is not part of the GA syntax (which explains the unusual syntax), but a placeholder replaced when a starter workflow is applied to a repository. It is also not covered in the GitHub Actions documentation, AFAICS. So if there is no equivalent in the GA context language, we will need to list the current and future defaults, like this:

```yaml
on:
  push:
    branches:
      - main
      - master
```
