### ISSUE TITLE
Upgrade the build-system section in pyproject.toml

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#635]
The `pyproject.toml` file in generated projects still uses the pre-Poetry 1.1 backend:

```toml
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

This should be:

```toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

The lock file already uses the new format, but it looks like we forgot to update this file 😕
