### ISSUE TITLE
Move linkcheck to a cronjob-style workflow

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#901]
The problem with running linkcheck within the Tests workflow is that a broken link will affect every PR, even when unrelated to docs.

Recent cases:

- pip.pypa.io: documentation restructured
- badgen.net: experiencing issues

There's also the issue of some links related to our own release not yet available when it's published.

A cronjob-workflow might also be a good idea for running tests with unpinned dependencies, or on the upcoming Python release.

**Comment by staticdev** [comment]
I just saw this issue and was thinking about that. There are actually two cases:

1. Independent of PR link broke (eg. Poetry website went offline)

Then a CRONjob would be handy for docs workflow.

2. PR changes something in the documentation and can introduce a broken link

Then it also makes sense to run linkcheck.

Quickly checking [triggers documentation](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions) I see there could be a condition for each case. Something like:

```
on:
  schedule:
    - cron:  '0 1 * * *'  # everyday at 1am
  push:
    paths:
      - '**.rst'
      - 'docs/**'  # this could be also used to run selectively docs-build?
```

I also like that you have a separate workflow on cookiecutter for docs. Maybe we could have the same on generated project?
